Merge feature/game_logic into development
Joseph-Burke/Tic-Tac-Toe pull request #3
Opened 2020-08-08 11:22 UTC by Joseph-Burke

The authors request to merge the feature/game_logic branch into the development branch having now completed the following work:

-  All game logic has been implemented, allowing the user to play a game of Tic, Tac, Toe with another human player.
-  All Rubocop offences have been addressed and the code now throws no errors.

2020-08-08 18:42 UTC, davidmrtz-dev requested changes
## Hi @Godswilly , @Joseph-Burke  .
### Very good job so far.

However, there are some issues that need to be addressed before move on to the next project.  👨‍💻  ⬇️ 

****

### **Please make the changes required and submit for re-review once you are ready!** 

****

### Status: Changes required. ♻️  
****

Happy coding!  💻  
Have a great day 🙂

If you need more clarifications kindly reach me on slack.
**[TSE:  David Elí]** 
Slack: @ David Eli Martinez Garcia

2020-08-08 18:48 UTC, davitomix commented on lib/game.rb
> +require_relative 'board'
When a tie game occurs, the game does not show that the game is a tie, it just ends its execution.
Optional:
You can add the necessary logic of asking players to start another game.
![Screen Shot 2020-08-08 at 1 46 42 PM](https://user-images.githubusercontent.com/52430951/89717607-c8218200-d97d-11ea-9056-6af086522b1a.png)

2020-08-08 18:52 UTC, davitomix commented
Please resolve the conflicts between branches to be able to execute the lints in the pull request.

2020-08-09 11:49 UTC, Joseph-Burke commented
Additional changes have now been made as requested by @davitomix.

- The mistake in the logic which meant the game.announce_draw method was not called has now been fixed. Now, a draw is announced in the terminal if the game is concluded without a winner.
- The development branch has been merged into the feature/game_logic branch. Conflicts have been resolved and GitHub Actions is now able to run Rubocop, with no offences detected.
- The optional task of allowing the player to restart the game will be addressed in the feature/readme_game_instructions branch when we consider "finishing touches" for the project.

<img width="344" alt="Screenshot 2020-08-09 at 12 40 06" src="https://user-images.githubusercontent.com/56026099/89731301-d931c800-da3d-11ea-80f4-cc91535ebb45.png">

2020-08-10 02:06 UTC, lekegitrepo commented
#### Hi @Joseph-Burke and @Godswilly :clap: :clap:
#### You have done an excellent work :100:  by implementing the required changes.
#### This project is approved :rocket:

#### _Reviewed by Temitayo Adeleke_.

2020-08-10 02:07 UTC, lekegitrepo approved these changes
#### Status: Approved

2020-08-10 06:25 UTC, merged